Repository DIT113-V22/group-11, pull requests merged in 2022-05, with the labels that each got.

#68 Deletion of joystick
  LittleDrivers/app/build.gradle
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
  LittleDrivers/settings.gradle
Labels: bug, Sprint 2 Task

#69 The new joystick
  .DS_Store
  LittleDrivers/app/build.gradle
  LittleDrivers/app/libs/joystickjhr.aar
  LittleDrivers/app/src/main/AndroidManifest.xml
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
Labels: Sprint 2 Task

#63 Camera feed connection
  arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
Labels: Sprint 2 Task

#85 Renamed the path from smartcar to LittleDrivers In android studios
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
Labels: Sprint 3 task

#82 Deleting the JoystickView directory from the project structure
  LittleDrivers/joystickView/.gitignore
  LittleDrivers/joystickView/build.gradle
  LittleDrivers/joystickView/proguard-rules.pro
  LittleDrivers/joystickView/src/androidTest/java/com/zerokol/views/joystickView/ExampleInstrumentedTest.java
  LittleDrivers/joystickView/src/main/AndroidManifest.xml
  LittleDrivers/joystickView/src/main/java/com/zerokol/views/joystickView/JoystickView.java
  LittleDrivers/joystickView/src/test/java/com/zerokol/views/joystickView/ExampleUnitTest.java
Labels: Sprint 3 task, CleanUp

#89 Fixed obstacle avoidance bug on joystick
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
Labels: Sprint 3 task, CleanUp

#95 Bug fix: The car no longer becomes still when detecting an obstacle.
  arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
Labels: bug, Sprint 2 Task, Sprint 3 task, CleanUp

#98 Warning Message
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
  LittleDrivers/app/src/main/res/values/strings.xml
Labels: Sprint 3 task

#101 Update and add small features
  README.md
Labels: Development, CleanUp

#104 Update SMCE_ultrasonic_sensor.ino
  arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
Labels: sprint3UserStories

#103 Displaying the speed of the car
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
Labels: sprint3UserStories

#106 Displaying distance on application
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
  LittleDrivers/app/src/main/res/values/strings.xml
  arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
Labels: Sprint 3 task

#105 Automated Tests
  LittleDrivers/app/build.gradle
  LittleDrivers/app/src/androidTest/java/com/example/littledrivers/MainActivityTest.kt
  LittleDrivers/app/src/main/AndroidManifest.xml
  LittleDrivers/app/src/main/res/layout/activity_main.xml
  LittleDrivers/build.gradle
  LittleDrivers/gradle/wrapper/gradle-wrapper.properties
Labels: Sprint 3 task

#107 Displaying a text next to the speed
  LittleDrivers/app/src/main/res/layout/activity_main.xml
Labels: sprint3UserStories

#108 Obstacle avoidance switch
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
  LittleDrivers/app/src/main/res/values/strings.xml
  arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
Labels: Sprint 3 task

#111 Clean up arduino sketch
  .github/workflows/arduino-build.yml
  arduino/smartcar/board_config.json
  arduino/smartcar/smartcar.ino
  arduino/smartcar/vehicle_config.json
Labels: CleanUp

#109 Home screen
  LittleDrivers/app/src/main/AndroidManifest.xml
  LittleDrivers/app/src/main/java/com/example/littledrivers/HomeActivity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Loading1Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Loading2Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Loading3Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Loading4Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/ProgressAnimation1.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/ProgressAnimation2.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/ProgressAnimation3.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/ProgressAnimation4.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/SplashActivity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme2Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme3Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme4Activity.java
  LittleDrivers/app/src/main/res/drawable-mdpi/_017513_bh6hirobaymax_1200.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/animated_driver.png
  LittleDrivers/app/src/main/res/drawable-mdpi/big_hero_6.JPG
  LittleDrivers/app/src/main/res/drawable-mdpi/black_home.png
  LittleDrivers/app/src/main/res/drawable-mdpi/cars.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/cars_background.webp
  LittleDrivers/app/src/main/res/drawable-mdpi/icons8_home_100.png
  LittleDrivers/app/src/main/res/drawable-mdpi/nemo_friends.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/nemo_loading_background.jpg
  LittleDrivers/app/src/main/res/drawable-mdpi/princess.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/princess_background.jpg
  LittleDrivers/app/src/main/res/drawable-mdpi/three_dots.png
  LittleDrivers/app/src/main/res/drawable/gradient.xml
  LittleDrivers/app/src/main/res/layout/activity_home.xml
  LittleDrivers/app/src/main/res/layout/activity_loading1.xml
  LittleDrivers/app/src/main/res/layout/activity_loading2.xml
  LittleDrivers/app/src/main/res/layout/activity_loading3.xml
  LittleDrivers/app/src/main/res/layout/activity_loading4.xml
  LittleDrivers/app/src/main/res/layout/activity_splash.xml
  LittleDrivers/app/src/main/res/layout/activity_theme1.xml
  LittleDrivers/app/src/main/res/layout/activity_theme2.xml
  LittleDrivers/app/src/main/res/layout/activity_theme3.xml
  LittleDrivers/app/src/main/res/layout/activity_theme4.xml
  LittleDrivers/app/src/main/res/values/strings.xml
  LittleDrivers/build.gradle
Labels: Sprint 3 task

#115 Update smartcar.ino
  arduino/smartcar/smartcar.ino
Labels: Sprint 3 task

#117 Adding a theme for screen 4.
  LittleDrivers/app/src/main/res/drawable-mdpi/cars_racing.png
  LittleDrivers/app/src/main/res/drawable-mdpi/red_home.png
  LittleDrivers/app/src/main/res/layout/activity_theme4.xml
Labels: Sprint 3 task

#120 Theme1
  LittleDrivers/app/src/main/res/drawable/arrow_down_darkpink.png
  LittleDrivers/app/src/main/res/drawable/arrow_left_darkpink.png
  LittleDrivers/app/src/main/res/drawable/arrow_right_darkpink.png
  LittleDrivers/app/src/main/res/drawable/arrow_up_darkpink.png
  LittleDrivers/app/src/main/res/drawable/darkpink_home.png
  LittleDrivers/app/src/main/res/drawable/disneybackground.jpg
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_down_50__1_dark.png
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_left_50_dark.png
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_right_50_dark.png
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_up_50.png
  LittleDrivers/app/src/main/res/layout/activity_theme1.xml
  LittleDrivers/app/src/main/res/values/colors.xml
  LittleDrivers/app/src/main/res/values/strings.xml
Labels: Sprint 3 task

#121 Theme2: Added theme number 2 of the app. This includes a new backgrou…
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_down_60.png
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_left_60.png
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_right_60.png
  LittleDrivers/app/src/main/res/drawable/icons8_chevron_up_60.png
  LittleDrivers/app/src/main/res/drawable/icons8_home_50.png
  LittleDrivers/app/src/main/res/drawable/papers_co_aw13_nemo_disney_film_anime_sea_illustration_art_blue_29_wallpaper.jpg
  LittleDrivers/app/src/main/res/layout/activity_theme2.xml
  LittleDrivers/app/src/main/res/values/colors.xml
Labels: Sprint 3 task

#124 Design for theme 3
  LittleDrivers/app/src/main/res/drawable/arrow_down_black.png
  LittleDrivers/app/src/main/res/drawable/arrow_left_black.png
  LittleDrivers/app/src/main/res/drawable/arrow_right_black.png
  LittleDrivers/app/src/main/res/drawable/arrow_up_black.png
  LittleDrivers/app/src/main/res/drawable/baymaxbackground.jpeg
  LittleDrivers/app/src/main/res/drawable/big_hero_6_background.jpeg
  LittleDrivers/app/src/main/res/layout/activity_loading3.xml
  LittleDrivers/app/src/main/res/layout/activity_theme3.xml
Labels: Sprint 3 task

#113 Update testing android.yml
  .github/workflows/android.yml
  .github/workflows/testing android.yml
  LittleDrivers/app/build.gradle
  LittleDrivers/app/src/androidTest/java/com/example/littledrivers/ExampleInstrumentedTest.java
  LittleDrivers/gradlew
Labels: Sprint 3 task

#126 Navigational tests
  LittleDrivers/app/src/androidTest/java/com/example/littledrivers/ExampleInstrumentedTest.java
  LittleDrivers/app/src/androidTest/java/com/example/littledrivers/MainActivityTest.kt
  LittleDrivers/app/src/androidTest/java/com/example/littledrivers/NavigationTest.kt
  LittleDrivers/app/src/main/res/layout/activity_home.xml
  LittleDrivers/app/src/main/res/layout/activity_theme1.xml
  LittleDrivers/app/src/main/res/layout/activity_theme2.xml
  LittleDrivers/app/src/main/res/layout/activity_theme3.xml
  LittleDrivers/app/src/main/res/layout/activity_theme4.xml
Labels: Sprint4UserStories

#128 Beep sound
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme2Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme3Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme4Activity.java
  LittleDrivers/app/src/main/res/raw/beep.mp3
Labels: Sprint 4 Task

#135 Fix Home Screen
  LittleDrivers/app/src/main/res/drawable-mdpi/_017513_bh6hirobaymax_1200.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/cars.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/nemo_friend.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/nemo_friends.jpeg
  LittleDrivers/app/src/main/res/layout/activity_home.xml
Labels: CleanUp, Sprint 4 Task

#136 Fixing speed bug
  arduino/smartcar/smartcar.ino
Labels: Sprint 4 Task

#138 Joystick citation
  LittleDrivers/app/build.gradle
Labels: CleanUp, Sprint 4 Task

#142 CurrentSpeedConstraint
  LittleDrivers/app/src/main/res/layout/activity_theme3.xml
Labels: CleanUp

#145 Update README - Intro, what, why, how and features
  README.md
Labels: CleanUp

#147 Distance and speed placement bug
  LittleDrivers/app/src/main/AndroidManifest.xml
  LittleDrivers/app/src/main/res/drawable-mdpi/bigherosixbackground.jpeg
  LittleDrivers/app/src/main/res/drawable-mdpi/white_arrow_up.png
  LittleDrivers/app/src/main/res/drawable-mdpi/white_minus.png
  LittleDrivers/app/src/main/res/drawable-mdpi/white_plus.png
  LittleDrivers/app/src/main/res/drawable-mdpi/whitearrowdown.png
  LittleDrivers/app/src/main/res/drawable-mdpi/whitearrowleft.png
  LittleDrivers/app/src/main/res/drawable-mdpi/whitearrowright.png
  LittleDrivers/app/src/main/res/drawable-mdpi/whitehome.png
  LittleDrivers/app/src/main/res/layout/activity_theme2.xml
  LittleDrivers/app/src/main/res/layout/activity_theme3.xml
  LittleDrivers/app/src/main/res/layout/activity_theme4.xml
Labels: bug, CleanUp, Sprint 4 Task

#150 Speed changing buttons background
  LittleDrivers/app/src/main/res/layout/activity_theme1.xml
  LittleDrivers/app/src/main/res/layout/activity_theme2.xml
  LittleDrivers/app/src/main/res/layout/activity_theme3.xml
  LittleDrivers/app/src/main/res/layout/activity_theme4.xml
Labels: CleanUp

#154 Fixed sound for theme 1
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java
Labels: bug, CleanUp, Sprint 4 Task

#157 Software architecture description
  README.md
Labels: CleanUp, Sprint 4 Task

#152 Update README.md
  README.md
Labels: CleanUp, Sprint 4 Task

#160 Making car's minimum speed zero
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme2Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme3Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme4Activity.java
  arduino/smartcar/smartcar.ino
Labels: bug, CleanUp, Sprint 4 Task

#151 Clean up
  LittleDrivers/app/src/androidTest/java/com/example/littledrivers/NavigationTest.kt
  LittleDrivers/app/src/main/AndroidManifest.xml
  LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme2Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme3Activity.java
  LittleDrivers/app/src/main/java/com/example/littledrivers/Theme4Activity.java
  LittleDrivers/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: Ongoing, CleanUp, Sprint 4 Task

#162 README.md updated with demo video
  README.md
Labels: Sprint 4 Task
